export default {
  "login": "Shivam330415",
  "id": 60098040,
  "node_id": "MDQ6VXNlcjYwMDk4MDQw",
  "avatar_url": "https://avatars.githubusercontent.com/u/60098040?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Shivam330415",
  "html_url": "https://github.com/Shivam330415",
  "followers_url": "https://api.github.com/users/Shivam330415/followers",
  "following_url": "https://api.github.com/users/Shivam330415/following{/other_user}",
  "gists_url": "https://api.github.com/users/Shivam330415/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Shivam330415/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Shivam330415/subscriptions",
  "organizations_url": "https://api.github.com/users/Shivam330415/orgs",
  "repos_url": "https://api.github.com/users/Shivam330415/repos",
  "events_url": "https://api.github.com/users/Shivam330415/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Shivam330415/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Shivam Gupta",
  "company": "Coding Brewing",
  "blog": "www.codingbrewing.in",
  "location": "Delhi",
  "email": 'admin@codingbrewing.in',
  "hireable": null,
  "bio": "I am android and iOS developer currently working as a freelancer😎",
  "twitter_username": 'codingbrewing',
  "public_repos": 5200,
  "public_gists": 125,
  "followers": 5020,
  "following": 0,
  "created_at": "2020-01-20T11:51:10Z",
  "updated_at": "2021-04-21T14:33:48Z"
}